### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jocca1985** [pensierinmusica/email-check#1]
I am getting 'false' for each address. (tried @toptal.com, @gmail.com, @yahoo.com).

**Comment by pensierinmusica** [comment]
First blind guess is that either your origin server is blacklisted, or port 25 is closed on your network (as mentioned in readme). Can you please copy / paste here the error you're getting? Thanks

**Comment by jocca1985** [comment]
Right, I tried through different ISP and it was working. Looks like port was closed.
Thanks a lot.

**Comment by pensierinmusica** [comment]
You're welcome! Cheers
