### ISSUE TITLE
works fun only for gmail

### ISSUE THREAD

**Issue by ziedg** [pensierinmusica/email-check#10]

**Comment by nova76** [comment]
Not yet.
email+something@gmail.com equivalent email@gmail.com, but check result false in the first case.

**Comment by ksushilmaurya** [comment]
yes, for me also, only it is working with gmail not for other providers.

**Comment by bhadresharya** [comment]
So is it gmail checker or email checker?

**Comment by pensierinmusica** [comment]
What email providers are supported doesn't depend from this library's code. It depends on whether the email service answers the `HELO` request or not.

**Comment by nova76** [comment]
> What email providers are supported doesn't depend from this library's code. It depends on whether the email service answers the `HELO` request or not.

Already const EMAIL_REGEX is bad, because the email+something@gmail.com is a valid email string, even if no one is using it yet.  Since the first test is a string test with EMAIL_REGEX constant, we do not get further tests.

**Comment by pensierinmusica** [comment]
@nova76 the `+` sign issue is already mentioned in https://github.com/pensierinmusica/email-check/issues/11
