### ISSUE TITLE
iam unable to use it with multiple email at a time

### ISSUE THREAD

**Issue by a4545** [pensierinmusica/email-check#12]

**Comment by a4545** [comment]
iam unable to validate multiple email at same time

**Comment by a4545** [comment]
`const email =["araj85501@gmail.com","nipiv60214@naymeo.com","abc@bbc.com"]
 email.map(data =>{
    var quote_str =  "'" + data + "'";

    console.log(quote_str)
  emailCheck(quote_str)
    .then(function (res) {
        console.log(res)
      // Returns "true" if the email address exists, "false" if it doesn't.
    })
    .catch(function (err) {
        console.log(err)
      if (err.message === 'refuse') {
        // The MX server is refusing requests from your IP address.
      } else {
        // Decide what to do with other errors.
      }
    });
})`

**Comment by pensierinmusica** [comment]
Hi,

The module is not designed to accept an array of emails as input. Because emails need to be checked one by one. 

If you have an array of emails to check, you can do something along these lines:

```js
(async () => {
  const result = {};
  for (email of emails) {
    const valid = await emailCheck(email);
    result[email] = valid;
  }
  // do what you need with result...
})();
```
