### ISSUE TITLE
Can this be used for client side?

### ISSUE THREAD

**Issue by pallaviMN** [pensierinmusica/email-check#3]
Hi Team,

Can this plugin be used for frontend development like AngularJS?

**Comment by pensierinmusica** [comment]
Hi, no this module currently only works server-side. If you'd like a client-side solution, consider using email address validation (e.g. through [HTML5 standard validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), or a [jQuery plugin](https://jqueryvalidation.org/email-method/)).

Cheers!
