### ISSUE TITLE
Question where FROM = XXXXXXXXX@gmail.com

### ISSUE THREAD

**Issue by prashantjain68** [pensierinmusica/email-check#5]
Hi,
This is an awesome and unique module which will immensely help me in my project.

I have one question: I have a gmail account and I want to set the "from" to that gmail account. Is it possible? Appreciate if you can share t=some code snippet around my use case.

Thanks

**Comment by pensierinmusica** [comment]
Hi,

Happy to hear that you find the moduke useful! Your question is already addressed in the docs: https://github.com/pensierinmusica/email-check#example

Anyways, it'd look something like this:

```js
emailCheck('mail@example.com', { from: 'XXXXXXXXX@gmail.com' })
```

Cheers!
